### ISSUE TITLE
Cant add / change icons and fonts

### ISSUE THREAD

**Issue by elclaudio** [Syrex-o/FhemNative#8]
Hi

Thanks you for this software, it's very promising.
Could you please add a way to use our own icons and fonts because the current useable set is very limited for home automation ?

And please keep it cloud free like fhem, don't let the app download stuff from the web, somes devices are only connected to the local network or firewalled. It would be better to have a dedicated folder for fonts and icons and let the user add he's own there.

Thanks again

**Comment by Syrex-o** [comment]
This is a thing, a lot of people are asking for. Currently I don`t see a reliable and standard way to import other icons.
May you have an idea?

**Comment by Syrex-o** [comment]
Closed. No reply.
